export const COLORS = {
  primary: "#1a3a5c",
  primaryLight: "#2a5a8c",
  accent: "#c0392b",
  accentLight: "#e74c3c",
  dark: "#1a1a1a",
  grey900: "#2d2d2d",
  grey700: "#4a4a4a",
  grey500: "#7a7a7a",
  grey300: "#b0b0b0",
  grey200: "#d4d4d4",
  grey100: "#e8e8e8",
  grey50: "#f4f5f7",
  white: "#ffffff",
  good: "#27ae60",
  bad: "#c0392b",
};

export const styles = {
  app: {
    fontFamily: "'Segoe UI', 'Helvetica Neue', sans-serif",
    background: `linear-gradient(135deg, ${COLORS.grey50} 0%, #dde4ec 100%)`,
    minHeight: "100vh",
    color: COLORS.dark,
  },
  header: {
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.grey900} 100%)`,
    color: COLORS.white,
    padding: "20px 28px",
    display: "flex",
    alignItems: "center",
    gap: "16px",
    boxShadow: "0 4px 20px rgba(0,0,0,0.25)",
  },
  headerIcon: {
    width: 44,
    height: 44,
    background: COLORS.accent,
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "22px",
    fontWeight: 700,
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: "20px",
    fontWeight: 700,
    letterSpacing: "-0.3px",
  },
  headerSub: {
    fontSize: "12px",
    color: COLORS.grey300,
    marginTop: 2,
  },
  tabs: {
    display: "flex",
    background: COLORS.white,
    borderBottom: `2px solid ${COLORS.grey200}`,
    padding: "0 12px",
    overflowX: "auto",
  },
  tab: (active) => ({
    padding: "14px 20px",
    fontSize: "13px",
    fontWeight: active ? 700 : 500,
    color: active ? COLORS.primary : COLORS.grey500,
    borderBottom: active ? `3px solid ${COLORS.accent}` : "3px solid transparent",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.2s",
    background: "none",
    border: "none",
    borderBottomStyle: "solid",
  }),
  formContainer: {
    maxWidth: 900,
    margin: "24px auto",
    padding: "0 16px",
  },
  card: {
    background: COLORS.white,
    borderRadius: "12px",
    boxShadow: "0 2px 16px rgba(0,0,0,0.08)",
    overflow: "hidden",
    marginBottom: 24,
  },
  cardHeader: {
    background: COLORS.primary,
    color: COLORS.white,
    padding: "16px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardHeaderTitle: {
    fontSize: "16px",
    fontWeight: 700,
  },
  cardHeaderBadge: {
    background: "rgba(255,255,255,0.15)",
    padding: "4px 12px",
    borderRadius: "20px",
    fontSize: "11px",
  },
  cardBody: {
    padding: "24px",
  },
  sectionTitle: {
    fontSize: "13px",
    fontWeight: 700,
    color: COLORS.primary,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    borderBottom: `2px solid ${COLORS.grey100}`,
    paddingBottom: 8,
    marginBottom: 16,
    marginTop: 24,
  },
  row: {
    display: "flex",
    gap: 16,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  field: (flex = 1) => ({
    flex,
    minWidth: 180,
  }),
  label: {
    display: "block",
    fontSize: "11px",
    fontWeight: 600,
    color: COLORS.grey700,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: 6,
  },
  required: {
    color: COLORS.accent,
    marginLeft: 2,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    border: `1.5px solid ${COLORS.grey200}`,
    borderRadius: "8px",
    fontSize: "14px",
    color: COLORS.dark,
    background: COLORS.grey50,
    outline: "none",
    transition: "border 0.2s",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "10px 12px",
    border: `1.5px solid ${COLORS.grey200}`,
    borderRadius: "8px",
    fontSize: "14px",
    color: COLORS.dark,
    background: COLORS.grey50,
    outline: "none",
    cursor: "pointer",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    border: `1.5px solid ${COLORS.grey200}`,
    borderRadius: "8px",
    fontSize: "14px",
    color: COLORS.dark,
    background: COLORS.grey50,
    outline: "none",
    minHeight: 80,
    resize: "vertical",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  checkbox: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: "14px",
    cursor: "pointer",
  },
  btnRow: {
    display: "flex",
    gap: 12,
    justifyContent: "flex-end",
    marginTop: 24,
    paddingTop: 16,
    borderTop: `1px solid ${COLORS.grey100}`,
  },
  btnPrimary: {
    padding: "12px 32px",
    background: COLORS.accent,
    color: COLORS.white,
    border: "none",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 2px 8px rgba(192,57,43,0.3)",
  },
  btnSecondary: {
    padding: "12px 24px",
    background: COLORS.grey100,
    color: COLORS.grey700,
    border: `1.5px solid ${COLORS.grey200}`,
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
  },
  statusBadge: (status) => ({
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: 700,
    color: COLORS.white,
    background: status === "GOOD" ? COLORS.good : COLORS.bad,
  }),
  tableWrap: {
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
  },
  th: {
    background: COLORS.primary,
    color: COLORS.white,
    padding: "10px 12px",
    textAlign: "left",
    fontWeight: 600,
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "10px 12px",
    borderBottom: `1px solid ${COLORS.grey100}`,
    verticalAlign: "top",
  },
  trAlt: {
    background: COLORS.grey50,
  },
  timestamp: {
    fontSize: "12px",
    color: COLORS.grey500,
  },
  submitted: {
    background: COLORS.good,
    color: COLORS.white,
    padding: "16px 24px",
    borderRadius: "10px",
    textAlign: "center",
    fontSize: "15px",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
};
